# Generated by Django 3.1.7 on 2021-05-14 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaStart', models.DateTimeField(auto_now_add=True)),
                ('areaID', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=20, unique=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Area',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('commonUserID', models.AutoField(primary_key=True, serialize=False)),
                ('commonUserName', models.CharField(max_length=20)),
                ('commonUserEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('commonUserImage', models.ImageField(upload_to='userImage')),
                ('commonUserPassword', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommonUser', to='USFP.area')),
            ],
            options={
                'db_table': 'CommonUser',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=10, unique=True)),
                ('tagShowNum',models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('suggestionID', models.AutoField(primary_key=True, serialize=False)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('deleteDate', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('commonUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Suggestion', to='USFP.commonuser')),
                ('tags', models.ManyToManyField(related_name='Suggestion', to='USFP.Tag')),
            ],
            options={
                'db_table': 'Suggestion',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('isAdmin', models.BooleanField(default=False)),
                ('commonUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='VerifiedUser', serialize=False, to='USFP.commonuser')),
                ('adminArea', models.ManyToManyField(related_name='VerifiedUser', to='USFP.Area')),
            ],
            options={
                'db_table': 'VerifiedUser',
            },
        ),
        migrations.CreateModel(
            name='SuggestionOperation',
            fields=[
                ('operationTakeDate', models.DateTimeField(auto_now_add=True)),
                ('suggestionOperaionID', models.AutoField(primary_key=True, serialize=False)),
                ('operationType', models.CharField(choices=[(1, 'delSuggestion'), (2, 'upSuggestion')], max_length=10)),
                ('content', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USFP.suggestion')),
                ('verifiedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SuggestionOperation', to='USFP.verifieduser')),
            ],
            options={
                'db_table': 'SuggestionOperation',
            },
        ),
        migrations.CreateModel(
            name='ReplySuggestion',
            fields=[
                ('selfSuggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='selfSuggestion', serialize=False, to='USFP.suggestion')),
                ('suggestionToReply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReplySuggestion', to='USFP.suggestion')),
            ],
            options={
                'db_table': 'ReplySuggestion',
            },
        ),
        migrations.CreateModel(
            name='CommonUserOperation',
            fields=[
                ('operationTakeDate', models.DateTimeField(auto_now_add=True)),
                ('commonUserOperationID', models.AutoField(primary_key=True, serialize=False)),
                ('operationType', models.CharField(choices=[(1, 'delUser'), (2, 'upUser')], max_length=10)),
                ('content', models.TextField()),
                ('commonUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USFP.commonuser')),
                ('verifiedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOperation', to='USFP.verifieduser')),
            ],
            options={
                'db_table': 'CommonUserOperation',
            },
        ),
        migrations.CreateModel(
            name='AreaOperation',
            fields=[
                ('operationTakeDate', models.DateTimeField(auto_now_add=True)),
                ('areaOperationID', models.AutoField(primary_key=True, serialize=False)),
                ('operationType', models.CharField(choices=[(1, 'delArea'), (2, 'upArea')], max_length=10)),
                ('content', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USFP.area')),
                ('verifiedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AreaOperation', to='USFP.verifieduser')),
            ],
            options={
                'db_table': 'AreaOperation',
            },
        ),
    ]
